=== Sefaria/Sefaria-Data/sources/Masechtot_Ketanot/Sefaria.dtd
<?xml encoding="UTF-8"?>

<!-- THIS DTD IS CREATED BY DCL FOR SEFARIA
 Version dated October 10,2016.
-->
<!-- Any change requests should go to Data Conversion Laboratory, Inc.
POC: Devorah Ashlem
Phone: 718 307-5720
E-mail: dashlem@dclab.com


-->


<!ELEMENT book (front,body,back)>

<!ELEMENT front (#PCDATA|chapter)*>
<!ELEMENT back (#PCDATA|chapter)*>


<!ELEMENT body (chapter*,commentaries?)>
<!ATTLIST book
  id CDATA #IMPLIED>

<!ELEMENT pgbrk (#PCDATA)>
<!ATTLIST pgbrk
	id NMTOKEN #REQUIRED
>

<!ELEMENT commentaries (commentary*)>
<!ELEMENT commentary (label?,author,(phrase|p|chapter)*)>
<!ATTLIST commentary
  id CDATA #IMPLIED>

<!ELEMENT author (#PCDATA)>

<!ELEMENT chapter (label?,(phrase|p|pgbrk|verse)*)>
<!ATTLIST chapter
  num NMTOKEN #REQUIRED>

<!ELEMENT verse (label?,p*,pgbrk*)>
<!ATTLIST verse
  num NMTOKEN #REQUIRED>

<!ELEMENT phrase (label?,dh?,comment)>
<!ATTLIST phrase
  id NMTOKEN #IMPLIED>

<!ELEMENT dh (#PCDATA)>

<!ELEMENT comment (#PCDATA|xref)*>

<!ELEMENT p (#PCDATA|xref|pgbrk)*>

<!ELEMENT xref (#PCDATA)>
<!ATTLIST xref
  rid NMTOKEN #REQUIRED>

<!ELEMENT label (#PCDATA)>

<!ELEMENT italic (#PCDATA)>
<!ELEMENT bold (#PCDATA)>
<!ELEMENT underline (#PCDATA)>
<!ELEMENT bold-italic (#PCDATA)>
<!ELEMENT sup (#PCDATA)>
<!ELEMENT sub (#PCDATA)>

<!ELEMENT fig (label?, caption?, img+) >
<!ATTLIST fig
	id ID #REQUIRED
        position (float|anchor) #REQUIRED 
	float CDATA #IMPLIED
>

<!ELEMENT caption (title?, p*) >
<!ELEMENT title (p*) >

<!ELEMENT img (#PCDATA)>
<!ATTLIST img
	src CDATA #REQUIRED
	width CDATA #IMPLIED
	height CDATA #IMPLIED
>

<!ELEMENT list (label?, title?, list-item+) >
<!ATTLIST list
	id ID #IMPLIED
	list-type (bullet | alpha | order | roman-upper | roman-lower | simple) #IMPLIED
>
<!ELEMENT list-item (label?, p+)>
<!ATTLIST list-item
	id ID #IMPLIED
>

=== Sefaria/Sefaria-Data/sources/Masechtot_Ketanot/XML/Nahalat_Yaakov_end_of_intro.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "sefaria.dtd">
<book id="Tractate-hakdama3">
<front/><body><chapter num="1">
<label>תשלום להקדמת ספר נחלת יעקב </label>
<p>
ובזה ישבתי פסוקי תהלים . חלקי ה׳ אמרתי לשמור דבריך חליתי פניך בכל לב חנני כאמרתך
.  ואקדים מ״ש מהר״ם אלשיך ז״ל בפסוקי משלי סימן ב׳ אם תבקשנה ככסף וכמטמונים תחפשנה כו׳ . הגם
שדרוש ההוא בא בארוכה לא אמנע מלהעתיק הדרוש הנכבד כי הוא מוסר נאה מאד . ומלמד לאדם דעת שאל
יתייאש אדם עצמו מלעסוק במה נפשו חשקה הן במקרא או במשנה בתלמוד ואגדה גם לחדש בהן מה שנראה
בעין שכלו ואל יאמר מי אנכי ואילו היה דבר חידוש ההוא מלתא מעליותא למה לא העלו הראשונים בשכלם
. אין זה כי אם רע לב ודברי היצר הרע . כי אולי זהו חלקו הניתן לו מסיני . וז״ל מהרמ״א זצ״ל על פסוקי
משלי הנ״ל : </p>
<p>או יאמר ויהיה ענין הכתובים דרוש נחמד . והוא בשום שכל והבין כי הלא יראה הרואה ד׳ חלוקי הבנות להשגות
התורה שניין דא מן דא . אחד היגיעה בה כדברי האומר זאת התורה אדם כי ימות באהל אין התורה מתקיימת
אלא במי שממית עצמו עליה . וכך היא דרכה של הורה פת במלח תאכל . יגעתי ומצאתי תאמין וכאלה רבים
. שנית יראת ה׳ כי ראשית חכמה יראת ה׳ כל שיראת חטאו קודמת כו׳ . שלישית שתלוי במקובל בהר סיני
כמו שאמרו ז״ל בשמות רבה כי כל מה שכל תלמיד עתיד להחדש בעוה״ז הכל קבלו נפשותם בסיני והוא שנשכח
וכל נפש חוזרת וזוכרת מה שקבלה בהר סיני וזה הדבר הוא אשר נראה כמה מדות בדעות יש מחזיק במקרא
ויש במשנה ויש בגמרא ויש באגדה ויש ימצא בו שכל מוליד ויכול להתחדש ויש לא יתחדש . כי הכל תלוי
כפי ייחס נפשו למעלה בחלקי פנימיות התורה . יש קצרי יד לא ישיגו רק עד מקרא . ויש למשנה . וההיקש
בשאר . ויש ניתן לו להתחדש כפי המתיחס אל בחינת נפשו והמגיע לחלקו רצונו יתברך שלא יתחדש בעולם
זולת על ידו וכעובדא דרבה בר נחמני <pgbrk id="118C"/>שיצאה נשמתו בטהור. ומה צורך הי׳ לו יתברך יכריע רבה
ב״נ . אך וודאי הי׳ מחלקו שלא יאות לחדש בעולם ע״י זולתו ובם הוא יתברך שמר יחוס זה לבלתי חתוך
הדין זולת על ידו כמבואר אצלנו יפה . רביעית אשר ידענו כי חכם או טפש אחד מהדברים שגוזר הוא יתברך
קודם יצירת הוולד . וראוי לדעת איך יצדקו ד׳ אלה . שאם הוא מקובל בסיני מה צורך אל היגיעה העצומה
שאמרו ז"ל וגם אל קדימת יראת ה׳ וגם כי היגיעה והיראת ה׳ הם ב׳ דברים בלתי מתאחדים ועוד שאם היא
גזרה בהולדה איך יתלה במה שקבלה נפשו מסיני ולמה יצטרך לגזור שנית מה שכבר ניתן לו מאז : </p>
<p>אך יהי׳ כי ארבעתם יצטרכו . כי אין ספק מאז עומדות היו נפשותינו במעמד הר סיני הלא נתייחס לכל נפש
ונפש חלק בבחינת התורה לפי בחינת יחס שורש נפשו שעל ידו יחדש הוא יתברך חדושים בתורתו המתייחס
אליו כי חלקו הנה . והנה אם האיש הזה אשר חלק לו בבינה סכל יהיה איכה ידע את הדבר אשר ניתן לו ואיככה
יוכל להבינו . ע״כ הוא יתברך בעת יצירת הוולד ההוא יגזור על הטיפה ההיא לפי ערך הצורך להשגת חלק
נפשו הניתנה לו מסיני בל יעצרנו טפשת לבו החומרי מהשיג אשר מאז קבלה נפשו והכנת הדעת . אמנם גם
שהיא ניתנה לו להשגת חלק נפשו בתורה עוד יד בחירתו נטויה לנטות אל עסק התורה ולהתבונן בה בינה
כתבונתו . או לעשות בכל מלאכה ותסכון לו מתת תבונתו לחשוב מחשבות לעשות בכל מלאכות מחשבות אשר
יבחר לו . אמנם גם אחרי השיג תכלית חידוד שכלו לא במהרה ימהר למצוא כל חלק אשר חלקו לו בבינה בהר
סיני כי הלא היא באמת כנבואה קטנה כי כדבר הזה האמור בחכמה נאמר שם בשמות רבה על הנבואה כי כל
מה שנבאו הנביאים קבלו נפשותם בסיני ואעפ״כ צריך הכנה ומירוק החומר וטוהר הנפש להנבא וההיקש
בתורה לפי ערכו גם שלא יצטרך אל כל הכנות הנבואה לא יבצר מהצטרך מירוק החומר . כי כשקבל הכח ההוא
בסיני הי׳ משולל חומר ועתה הוא מעכב כאשר יעכב בנבואה שעל כן בחלום ידבר הוא יתברך בנביאים בעת
תפרד בצד מה הנפש ממנו . וגם צריך הכנת וטוהר הנפש כי הלא חלק התורה הנשפע בו משורש נשמתו הדביקה
בו יתברך הוא לכן לפי דביקת הנפש אל מקורה תשאב משם מנת כוס ישועות המתייחס אליה . ולפי מירוק
החומר בל יעצרנו הגשם מלערות עליו רוח ממרום . ע״כ בגלל הדבר הזה צריך ב׳ דברים אחד יגיעה רבה
למרק החומר כמאמר חז״ל פת במלח כו׳ ובתורה אתה עמל ככל אשר יעשה איש למצוא כסף ומטמונים ובעשות
כן ימצא את אשר ניתן לו . ובזה הטיבו אשר דברו יגעתי ומצאתי תאמין ולא אמר יגעתי וידעתי או למדתי
רק ומצאתי לומר כי גם חלקך האבוד ממך כעת צריך יגיעה למצוא אותו . שנית לטהר הנפש לשלשל על ידה
שפע חלקו יתברך כי דבק בו הוא כי עד כה אין חלקה בה רק בכח וצריך יערה עליו רוח ממרום מהביאו אל
הפועל כנבואה אשר בנפש הנביא בכח וע״י הכנות שב ה׳ ומדבר בו להביאו אל הפועל כן בתורה והוא בהקנות
בה יראת ה׳ ולפי גדר המירוק ויגיעה בה ויראת ה׳ תהא השגתו בה אם מעט ואם הרבה . ובדבר הזה צדקו
יחדיו כל הד׳ דברים איש על מקומו עכ׳׳ל הרמ״א ז״ל :
</p>
<p>
 ובזה מיושבים פסוקי תהלים הנ״ל וכך הם דברי
המשורר ע״ה חלקי ה׳ ר״ל חלקי הניתן לי מה׳ במעמד הר סיני וגם בשעת לידה נתן לי לב שכל להבין ולהשכיל
. אותו החלק אמרתי לשמור דבריך ולתור בחכמה ובדעת להבין עמקי סודות התורה אבל לא לחשוב מחשבות
ולעסוק בחכמתי במלאכת עוה״ז . והוסיף עוד ואמר חליתי פניך בכל לב לכבוש יצרי ולזכך חומרי כדי
להוציא אל הפועל לעשות כאמרתך כלומר כמו שאמרת עלי בשעת יצירה . וכדברים האלה יש לכוון בדברי
הנביא ירמיה ע״ה באומרו חלקי ה׳ אמרה נפשי על כן אוחיל לו ר״ל נפשי אמרה לי שכבר ניתן לי חלקי
במעמד הר סיני בנבואה ובתורה ע״כ אוחיל לו להוציא מחשבתי אל הפועל ע״י כל ההכנות הצריכים לזה
: <pgbrk id="119A"/> </p></chapter>
</body>
<back/></book>

=== Sefaria/Sefaria-Data/sources/Masechtot_Ketanot/XML/Nahalat_Yaakov_intro_to_Gerim.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "sefaria.dtd">
<book id="Tractate-hakdama4">
<front/><body><chapter num="1">
<label>הקדמה למסכת גרים </label>
<p> מצאתי בספר שמחת הרגל נדפס בליוורני . אשר חבר מהור׳׳ר חיים יוסף דוד אזולאי מיקירי
אנשי ירושלים עה״ק תוב״ב ובסוף ספרו נדפס מסכת גרים הביאה הרב בעל מגדל עוז כמה פעמים בפי״ג
מהלכות אסורי ביאה להרמב״ם ז״ל . אכן לא ידע אנוש ערכה . והיא עלומה . והמחבר ספר הנ"ל הוציאה לאורה
וכתב בוה הלשון . מס׳ זו מהמסכת קטנות והיא לא נדפס״ה והועתקה מהש״ס המצויה בעיר פפערשא כתוב
על קלף בעיר פאריץ בשנת ק״ג לאלף הששי לאחד מקרובי רבינו שמשון משאנץ . והזכרתי ש״ס זה בספרי
הקטן שער יוסף . גם הוזכר בספר קרבן נתנאל בדף האחרון עכ״ל ספר הנ״ל אכן מס׳ זו הציגוה ערומה
. כיום הולדה . מבלי פירוש לדבריה . כדרך כל ריעותיה . שאר מס' קטנות נעו מעגלותיה . על כן נתתי אל
לבי דברי חז״ל המתחיל במצוה אומרים לו גמור . וכאשר פרשתי בעז״ה כל המסכת קטנות בפירוש קל ונכון
ככה עשיתי למס׳ הזאת לבארה באר היטב ע"פ ש״ס ופוסקים כיד ה׳ הטובה עלי והראיתי בה מבוא כל הלכה
איה מקום כבודה בש״ס למען ירוץ הקורא בה : </p>


<p>גם אלה דברי המחבר ספר נחלת יעקב הקטן המכונה יאקאב ב׳׳ה ברוך נוימבורג ז״ל מתושבי ק׳׳ק אופיבאך
בשנת און וחקר ותק"ן לפ״ק : <pgbrk id="119B"/> </p></chapter>
</body>
<back/></book>
