=== Sefaria/Sefaria-Data/dictionaries/Jastrow/data/00-Separate XML/sefaria_dictionary.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT book (front,body,back)>
<!ATTLIST book
  xmlns CDATA #FIXED ''
  id ID #REQUIRED>

<!ELEMENT front (chapter)*>
<!ATTLIST front
  xmlns CDATA #FIXED ''>

<!ELEMENT body (chapter)*>
<!ATTLIST body
  xmlns CDATA #FIXED ''>

<!ELEMENT back (chapter)*>
<!ATTLIST back
  xmlns CDATA #FIXED ''>

<!ELEMENT chapter (title? ,(p|entry|pgbrk)*)>
<!ATTLIST chapter
  xmlns CDATA #FIXED ''
  num CDATA #IMPLIED>

<!ELEMENT title (#PCDATA)>
<!ATTLIST title
  xmlns CDATA #FIXED ''>

<!ELEMENT p (#PCDATA|bold|italic|sub|sup|underline|xref|pgbrk)*>
<!ATTLIST p
  xmlns CDATA #FIXED ''>

<!ELEMENT entry ((head-word*,hw-number?,pos?,plural-form?,language-key?,language-reference?)*,plural-form?,
                 senses?,pgbrk?,notes?,plural-form?,binyan*,derivatives?)>
<!ATTLIST entry
  xmlns CDATA #FIXED ''
  indent CDATA #IMPLIED 
  id ID #REQUIRED>

<!ELEMENT pgbrk EMPTY>
<!ATTLIST pgbrk
  xmlns CDATA #FIXED ''
  id ID #REQUIRED>

<!ELEMENT head-word (#PCDATA)>
<!ATTLIST head-word
  xmlns CDATA #FIXED ''>

<!ELEMENT hw-number (#PCDATA)>
<!ATTLIST hw-number
  xmlns CDATA #FIXED ''>

<!ELEMENT plural-form (#PCDATA|xref)*>
<!ATTLIST plural-form
  xmlns CDATA #FIXED ''>

<!ELEMENT binyan ((language-key|binyan-form|binyan-name)*,senses)>
<!ATTLIST binyan
  xmlns CDATA #FIXED ''>

<!ELEMENT derivatives (#PCDATA|bold|italic|sub|sup|underline|xref|pgbrk)*>
<!ATTLIST derivatives
  xmlns CDATA #FIXED ''>

<!ELEMENT binyan-form (#PCDATA)>
<!ATTLIST binyan-form
  xmlns CDATA #FIXED ''>

<!ELEMENT binyan-name (#PCDATA)>
<!ATTLIST binyan-name
  xmlns CDATA #FIXED ''>

<!ELEMENT bold (#PCDATA)>
<!ATTLIST bold
  xmlns CDATA #FIXED ''>

<!ELEMENT sub (#PCDATA)>
<!ATTLIST sub
  xmlns CDATA #FIXED ''>

<!ELEMENT underline (#PCDATA)>
<!ATTLIST underline
  xmlns CDATA #FIXED ''>

<!ELEMENT italic (#PCDATA)>
<!ATTLIST italic
  xmlns CDATA #FIXED ''>

<!ELEMENT sup (#PCDATA)>
<!ATTLIST sup
  xmlns CDATA #FIXED ''>

<!ELEMENT pos (#PCDATA|xref)*>
<!ATTLIST pos
  xmlns CDATA #FIXED ''>

<!ELEMENT xref (#PCDATA)>
<!ATTLIST xref
  xmlns CDATA #FIXED ''
  rid IDREF #REQUIRED>

<!ELEMENT language-key (#PCDATA)>
<!ATTLIST language-key
  xmlns CDATA #FIXED ''>

<!ELEMENT language-reference (#PCDATA|xref|italic|bold)*>
<!ATTLIST language-reference
  xmlns CDATA #FIXED ''>

<!ELEMENT senses (sense)*>
<!ATTLIST senses
  xmlns CDATA #FIXED ''>

<!ELEMENT sense (number?,pos?,language-key?,definition,notes?)>
<!ATTLIST sense
  xmlns CDATA #FIXED ''>

<!ELEMENT number (#PCDATA)>
<!ATTLIST number
  xmlns CDATA #FIXED ''>

<!ELEMENT alternative (#PCDATA|bold|italic|sub|sup|underline|xref|pgbrk)*>
<!ATTLIST alternative
  xmlns CDATA #FIXED ''>

<!ELEMENT definition (#PCDATA|bold|italic|sub|sup|underline|xref|pgbrk|alternative|pos|language-key|language-reference|plural-form)*>
<!ATTLIST definition
  xmlns CDATA #FIXED ''>

<!ELEMENT notes (#PCDATA|bold|italic|sub|sup|underline|xref|pgbrk|plural-form)*>
<!ATTLIST notes
  xmlns CDATA #FIXED ''>

=== Sefaria/Sefaria-Data/dictionaries/Jastrow/data/00-Separate XML/forematter.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE book SYSTEM "sefaria_dictionary.dtd">
<book id="Jastrow_Dictionary">
<front>
<chapter>
<p>ספר המילים
<pgbrk id="pgiii"/></p>
<p>DICTIONARY</p>
<p>of the</p>
<p>Targumim, Talmud Bavli,</p>
<p>Talmud Yerushalmi</p>
<p>
<italic>and</italic></p>
<p>Midrashic Literature</p>
<p>MARCUS JASTROW</p>
<p>
<pgbrk id="pgiv"/>© Copyright 1971, 2004</p>
<p>ALL RIGHTS RESERVED.</p>
<p>NO PART OF THIS PUBLICATION MAY BE TRANSLATED, REPRODUCED, STORED IN A RETRIEVAL SYSTEM OR TRANSMITTED, IN ANY FORM OR BY ANY MEANS, ELECTRONIC, MECHANICAL, PHOTOCOPYING, RECORDING, OR OTHERWISE, WITHOUT PERMISSION IN WRITING FROM THE PUBLISHER.</p>
<p>ISBN: 1-932443-20-7</p>
<p>Phone: 800-972-6201</p>
<p>Fax: 718-972-6204</p>
<p>
<italic>Manufactured in the United States of America</italic></p>
<p>
<pgbrk id="pgv"/>
<bold>Preface.</bold></p>
<p>The literature embraced in this Dictionary covers a period of about one thousand years, and contains Hebrew and Aramaic elements in about equal proportions. The older Hebrew elements, which may conveniently be called the Mishnaic, and can in part be traced back to the first, if not to the second, century B. C. E., may be considered a continuation of the Biblical Hebrew—Biblical Hebrew tinged with Aramaisms. It is therefore apt to throw light, more directly than its successor, on many obscure words and passages in the Bible; nevertheless, the material for Biblical exegesis deposited in the later literature is an inexhaustible mine, which still awaits exploitation by sympathetic students. Besides the Mishnah and the Tosefta, the Mishnaic period embraces Sifra and Sifré, Mekhilta, and the older elements preserved in the Gemara, of which the prayers incidentally quoted are a very essential and interesting part.</p>
<p>The later Hebrew elements in the Gemara and in the Midrashim lead down to the fifth and the eighth century respectively, and to a larger degree than the earlier Hebrew sections are mixed with Aramaic elements, and with foreign words borrowed from the environment and reflecting foreign influences in language as well as in thought. The Aramaic portions of the literature under treatment comprise both the eastern and the western dialects.
<sup>1</sup> Owing to the close mental exchange between the Palestinian and the Babylonian Jews, these dialects are often found inextricably interwoven, and cannot be distinguished lexicographically.</p>
<p>The subjects of this literature are as unlimited as are the interests of the human mind. Religion and ethics, exegesis and homiletics, jurisprudence and ceremonial laws, ritual and liturgy, philosophy and science, medicine and magics, astronomy and astrology, history and geography, commerce and trade, politics and social problems, all are represented there, and reflect the mental condition of the Jewish world in its seclusion from the outer world, as well as in its contact with the same whether in agreement or in opposition.</p>
<p>
<pgbrk id="pgvi"/>Owing to the vast range and the unique character of this literature, both as to mode of thinking and method of presentation, it was frequently necessary to stretch the limits of lexicography and illustrate the definitions by means of larger citations than would be necessary in a more familiar domain of thought. Especially was this the case with legal and with ethical subjects.</p>
<p>Archæological matters have often been elucidated by references to Greek and Roman customs and beliefs.</p>
<p>The condition of the texts, especially of the Talmud Yerushalmi and of some of the Midrashim, made textual criticism and emendations inevitable, but the dangers of arbitrariness and personal bias had to be guarded against. Happily there were, in most cases, parallels to be drawn upon for the establishment of a correct text, and where these auxiliaries failed, the author preferred erring on the conservative side to indulging in conjectural emendations. For the Babylonian Talmud Raphael Rabbinowicz’s Variae Lectiones was an invaluable aid to the author.</p>
<p>The etymological method pursued in this Dictionary requires a somewhat fuller explanation than is ordinarily embodied in a preface.
<sup>1</sup></p>
<p>The Jewish literature here spoken of is specifically indigenous, in which respect it is unlike the Syriac literature contemporary with it, which is mainly Christian, and as such was influenced, not only in thought but also in language, by the Greek and Latin tongues of the religious teachers of a people itself not free from foreign admixtures. Foreign influences came to Jewish literature merely through the ordinary channel of international intercourse. It is for this reason, if for no other, that the Jewish literature of post-Biblical days down to the ninth century may be called original. Hence it is natural to expect that, in extending the horizon of thought, it also extended its vocabulary on its own basis, employing the elements contained in its own treasury.</p>
<p>Starting from such premises, the investigator had to overhaul the laws regulating the derivation of words whose etymology or meaning is unknown from known Semitic roots; every word of strange appearance had to be examined on its merits both as to its meaning or meanings and as to its origin; the temptation offered by phonetic resemblances had to be resisted, and the laws of word-formation common to all other original languages as well as the environment in which a word appears had to be consulted before a conclusion could be reached. The foremost among these laws is that a word is imported into one language from another with the importation of the article it represents or of the idea it conveys. Unless these conditions of importation are apparent, the presumption should be in favor of the home market.</p>
<p>Take e.g. the word סימטא and its dialectic equivalent איסמטא, which means 
<pgbrk id="pgvii"/>(a) a recess, an alley adjoining the market place to which the merchants retire for the transaction of business, also the trader’s stand under the colonnade, and (b) an abscess, a carbuncle. The Latin 
<italic>semita</italic>, which since Musafia has been adopted as the origin of 
<italic>sim</italic>
<italic>ṭ</italic>
<italic>a</italic>, offers hardly more than an assonance of consonants: a footpath cannot, except by a great stretch, be forced into the meaning of a market stand; and what becomes of 
<italic>sim</italic>
<italic>ṭ</italic>
<italic>a</italic> as 
<italic>abscess</italic>? But take the word as Semitic, and סמט, dialectically = 
<sup>1</sup>שמט, offers itself readily, and as for the process of thought by which ‘recess’, ‘nook’, goes over into ‘abscess’ in medical language, we have a parallel in the Latin ‘abscessus.’ How much Latin medical nomenclature may have influenced the same association of ideas among the Jews is a theme of speculation for students of comparative philology or of the physiology of language.</p>
<p>A superficial glance at the vocabulary of this Dictionary will convince the reader that the example here given represents an extremely numerous class. The cases may not always be so plain, and the author is prepared for objections against his derivations in single instances, but the number of indisputable derivations from known Semitic roots remains large enough to justify the method pursued.</p>
<p>The problem becomes more complicated when both the meaning and the origin of words are unknown. Such is the case e.g. with the word אספירס in the phrase (Num. R. s. 4
<sup>20</sup>) הופך אספירס ומשוור, he turned the 
<italic>isperes</italic> and leaped. Levy, guided by Musafia, resorts to σφυρόν, 
<italic>ankle;</italic> others suspect in it the name of a garment, σπεῖρος, a rare form for σπεῖρον. But the phrase itself and the context in which it appears indicate a native word, and this is found in the stem פ־ס, of which אספרס is an ‘Ispeel’ noun, that is to say, a noun formed from the enlarged stem ספ־ס. As פֶּרֶס or פַּרְסָה is the cloven foot, the latter being also applied to the human foot (Sifré Deuteronomy 2), so אִסְפֶּירֶס is the front part of the foot, where the toes begin to separate. The phrase quoted is to be translated, ‘he (David) inverted the front part of his foot’, i.e. stood on tiptoe, ‘and leaped’ (danced).</p>
<p>We meet with the same stem in the Aramaic, אספריסא. Referring to Lamentations III, 12, ‘he has bent his bow and set me (literally: made me to stand) as a mark for the arrow’, one Amora is recorded in the Midrash (Lamentations Rabbah a. l.) as having explained 
<italic>kamma</italic>
<italic>tt</italic>
<italic>ara la</italic>
<italic>ḥ</italic>
<italic>ets</italic> by כבורמא לאספריסא. Another is quoted as saying, ‘like the pole of the archers (the Roman palus) at which all aim, but which remains standing.’ What is בורמא? and what is אספריסא? The medieval Jewish commentators frankly admit their ignorance. Musafia, however, reads פרמא, maintaining that he had found it in some editions, and refers to Latin 
<italic>parma</italic>, explaining 
<italic>isp’risa</italic> as 
<italic>sparus</italic>, and translating, ‘as the shield to the spear.’ Ingenious, indeed! But on closer inspection this explanation is beset with intrinsic difficulties. To begin with, 
<italic>parma</italic> as shield does not appear in the Talmudic literature again, from which we may infer that it was not generally known to the Jews in their 
<pgbrk id="pgviii"/>combats with the Romans. Furthermore, the
